### ISSUE TITLE
How to handle ampersands in titles?

### ISSUE THREAD

**Issue by stemid** [Guts/mkdocs-rss-plugin#19]
My RSS feed is invalid because there are ampersands in titles.

Afaik there is no conversion done in mkdocs of special characters, where should this be handled? Should mkdocs-rss-plugin perhaps convert them?

**Comment by Guts** [comment]
ampersands are invalidd characters in XML (see: https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML)

Did you try with &amp; ?

**Comment by stemid** [comment]
Yes I know they're invalid but am I supposed to enter &amp; into my documents myself? That seems cumersome in the long run.

**Comment by Guts** [comment]
@stemid could you provide URL for your website sources please? It would help me to better understand (which part of the output XML is about.

If the invalid character are inside the item description, you can use the meta.description to override which content is used to fill the feed. See: https://guts.github.io/mkdocs-rss-plugin/configuration/#item-description-length

A long term solution would be:

- apply a safe filter in jinja2 template on item title too
- use the HTML output instead of the markdown for the item description when meta.description is not present

**Comment by stemid** [comment]
@Guts I only had one page with an ampersand in the title, added the meta plugin, added both title and description to that page.

So it looks like this;

```
$ head docs/technical/active_directory/ad_autentisering_i_rhel_7_och_ubuntu_14_04.md 
---
description: AD Autentisering i RHEL 7 & Ubuntu 14.04
title: AD Autentisering i RHEL 7 &amp; Ubuntu 14.04
---
```

So it's a bit inconsistent, but it works without errors. 

I tried looking at util.py but can't figure out where this sanitation of ampersands is going on. Maybe in the meta plugin? Because description is being replaced with &amp; while in title I had to do it myself.

[Here](https://stefan.midjich.name/technical/active_directory/ad_autentisering_i_rhel_7_och_ubuntu_14_04/) is the actual page, with a link to its source included. And [here is a direct link](https://stefan.midjich.name/feed_rss_updated.xml) to the fixed rss feed, so no error.

**Comment by Guts** [comment]
> So it's a bit inconsistent, but it works without errors.

Good news 🥳 . With #21, it will be more consistent.

> I tried looking at util.py but can't figure out where this sanitation of ampersands is going on. Maybe in the meta plugin? Because description is being replaced with & while in title I had to do it myself.

As I said, it's not in Python code but in [jinja template](https://github.com/Guts/mkdocs-rss-plugin/tree/master/mkdocs_rss_plugin/templates).

Done with #21.

> Here is the actual page, with a link to its source included. And here is a direct link to the fixed rss feed, so no error.

Looking at your mkdocs.yml, the feed can't be compliant because of various missing attributes: description, site_url, site_author... You should refer to the documentation with mandatory an recomended fields at least: https://guts.github.io/mkdocs-rss-plugin/configuration/#mkdocs-configuration.

**Comment by Guts** [comment]
@stemid is that okay for you?

**Comment by stemid** [comment]
@Guts 0.9.0 is looking good to me.

I had to use a virtualenv and install GitPython because my Fedora 31 GitPython was too old, 3.0.x instead of 3.1.x.

Then I went into my markdown docs and changed amp to & and the feed is rendering without errors.

I'm pushing this to my public site so it might be hours before the cache is fresh.

**Comment by Guts** [comment]
Cool. So I can close here.
