### ISSUE TITLE
Multiple authors / RSS email

### ISSUE THREAD

**Issue by carried-away** [Guts/mkdocs-rss-plugin#275]
Hello again,

When there are multiple authors, the RSS email will concatenate both strings in the from field.

E.G.

author:
    - Mary Jane
    - Peter Parker

Email = From: Mary JanePeter Parker

I tried to cheat and put a space at the end of the names in the yaml file, but it sanitizes it. Is there a good way of getting a space between each author if multiple?

**Comment by Guts** [comment]
Hello @carried-away 

Sorry for the delayed answer.

Can you share your whole project or at least a full page YAML frontmatter? It's pretty hard to understand what's wrong. Try to fill your issue with valuable information: expected behavior, used, version, etc.

Do you have a frontmatter like this https://github.com/Guts/mkdocs-rss-plugin/blob/main/docs/index.md?plain=1#L3-L5?

**Comment by Guts** [comment]
No feedback for months, I'm closing here.
