### ISSUE TITLE
TypeError: strptime() argument 1 must be str, not datetime.datetime

### ISSUE THREAD

**Issue by ZhiyuanChen** [Guts/mkdocs-rss-plugin#290]
It seems 1.13.0 introduces a few new bugs

My pipeline worked fine, but is complaining now. 

https://github.com/DLS5-Omics/multimolecule/actions/runs/9465496343/job/26075394011

**Comment by Guts** [comment]
Hey @ZhiyuanChen 

Is your issue still active? Have you seen my comment on your PR https://github.com/Guts/mkdocs-rss-plugin/pull/291#issuecomment-2161257314?

**Comment by Guts** [comment]
I investigated a little further because the error seems strange to me since the default value of `date_from_meta.default_time` which is used in your configuration. 
After looking at your build in verbose mode, it appears that the doc is built 2 times.

It seems that the problem comes from the i18n plugin. By deactivating it, the build goes smoothly.
